### ISSUE TITLE
Fix accidental convert to private access

### ISSUE THREAD

**Issue by JiwoonKim** [JiwoonKim/interview-cake#2]
@ninjayoto

Hello, I would really appreciate it if you could remove your forked repository https://github.com/ninjayoto/interview-cake of this original repository.

I've accidentally converted this to a private repo without knowing that you had forked from it and now it seems to have lost the link between the two. Sorry for the inconvenience, but I would really appreciate it if you could remove the forked repository. If you prefer having a forked version of the repo, please remove the current forked repository and feel free to fork again. 

P.S. I referred to you via the issue since I could not find a contact to your email.

**Comment by ninjayoto** [comment]
@JiwoonKim done!
